apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::339872421447:role/eksctl-simple-jwt-api-7-nodegroup-NodeInstanceRole-16NGOVN71EEEI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::339872421447:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-28T12:13:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1016"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 2943e211-7d51-491b-a31e-5e27f9954e88
